server:
  port: 8989

spring:
  application:
    name: woosso_scg
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: http://localhost:8081/
              predicates:
                - Path=/scg/api/user/**
              filters:
                - StripPrefix=1




logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug